-- DM8 least-privilege projection for the Skillify db-readonly MCP adapter.
-- The runtime account receives SELECT on these views only, never on base tables.

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_SKILL_INDEX AS
SELECT NAMESPACE, NAME, VERSION, DESCRIPTION, AUTHOR, TAGS, CHECKSUM,
       RELEASE_URL, PUBLISHED_AT, YANKED
FROM SKILLIFY_TEST.SKILL_INDEX;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_SKILL_EVENTS AS
SELECT ID, NAMESPACE, NAME, VERSION, EVENT_TYPE, SUCCESS, OCCURRED_AT
FROM SKILLIFY_TEST.SKILL_EVENTS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_BINDINGS AS
SELECT ENDPOINT_ID, LABEL, ONLINE, LAST_SEEN_AT
FROM SKILLIFY_TEST.ENDPOINT_BINDINGS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_TASKS AS
SELECT TASK_ID, ENDPOINT_ID, WORKFLOW_ID, WORKFLOW_VERSION, WORKSPACE_ALIAS,
       STATE, STATE_VERSION, REVOKED, APPROVAL_REQUIRED, ISSUED_AT, EXPIRES_AT,
       CREATED_AT, UPDATED_AT, RUNTIME, LEASE_OWNER, LEASE_EXPIRES_AT,
       HEARTBEAT_AT, EXECUTION_MODE, COLLABORATION_RUNTIME, PREFERRED_CLI
FROM SKILLIFY_TEST.ENDPOINT_TASKS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_TASK_EVENTS AS
SELECT ID, TASK_ID, EVENT_TYPE, OCCURRED_AT, EVENT_ID, WORKER_ID,
       WORK_PACKAGE_ID, STAGE
FROM SKILLIFY_TEST.ENDPOINT_TASK_EVENTS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_TEAM_TASKS AS
SELECT TASK_ID, EXECUTION_MODE, COLLABORATION_RUNTIME, PREFERRED_CLI,
       STATE, CREATED_AT, UPDATED_AT
FROM SKILLIFY_TEST.ENDPOINT_TEAM_TASKS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_TEAM_WORKER_EVENTS AS
SELECT ID, EVENT_ID, TASK_ID, EVENT_TYPE, WORKER_ID, WORK_PACKAGE_ID,
       STAGE, OCCURRED_AT
FROM SKILLIFY_TEST.ENDPOINT_TEAM_WORKER_EVENTS;

CREATE OR REPLACE VIEW SKILLIFY_TEST.MCP_ENDPOINT_WORK_PACKAGES AS
SELECT ID, PACKAGE_ID, TASK_ID, ACCESS, PARALLELIZABLE, CONFIRMED, READ_ONLY
FROM SKILLIFY_TEST.ENDPOINT_WORK_PACKAGES;

GRANT SELECT ON SKILLIFY_TEST.MCP_SKILL_INDEX TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_SKILL_EVENTS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_BINDINGS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_TASKS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_TASK_EVENTS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_TEAM_TASKS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_TEAM_WORKER_EVENTS TO SKILLIFY_MCP_RO;
GRANT SELECT ON SKILLIFY_TEST.MCP_ENDPOINT_WORK_PACKAGES TO SKILLIFY_MCP_RO;

COMMIT;
